# fly.toml app configuration file generated for aging-provision on 2025-06-21T15:51:24+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aging-provision'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  PYTHONUNBUFFERED = "1"

[[services]]
  internal_port = 8501
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80